// // src/actions/types.js
// export const FETCH_BLOOD_DONATIONS_REQUEST = 'FETCH_BLOOD_DONATIONS_REQUEST';
// export const FETCH_BLOOD_DONATIONS_SUCCESS = 'FETCH_BLOOD_DONATIONS_SUCCESS';
// export const FETCH_BLOOD_DONATIONS_FAILURE = 'FETCH_BLOOD_DONATIONS_FAILURE';
